// GENERADO por `npm run sync` desde el diccionario de la web — no editar a mano.
//
// Las traducciones de lo que va escrito dentro de las pantallas nativas.
// Las mandaba la web por el puente, así que el teléfono no sabía decir
// «Balance» en inglés hasta que la web arrancaba: al abrir la app, lo
// nativo salía en español un momento. Y el día que el webview se quite, se
// quedaba sin idioma.

import Foundation

enum CNTextosGenerados {

    /// Español → inglés.
    static let en: [String: String] = [
        "¡Subiste": "You are up",
        "¿Cómo es?": "What is it?",
        "¿Eliminar movimiento?": "Delete this transaction?",
        "¿Qué quieres agregar?": "What do you want to add?",
        "{n} sin usar": "{n} unused",
        "% de tus ingresos": "% of your income",
        "A este ritmo llegas en": "At this pace you get there in",
        "Abrir": "Open",
        "Activa al menos un método: al entrar te pediremos un código además de la contraseña.": "Turn on at least one method: when signing in we’ll ask for a code besides your password.",
        "Activada": "On",
        "Activo": "On",
        "Agotado": "Used up",
        "Agregar tarjeta": "Add a card",
        "Ahora no": "Not now",
        "Ahorro": "Savings",
        "Ahorro e inversión": "Savings and investments",
        "Al cambiarlo, iOS avisa una vez de que el icono cambió. Es normal y lo pregunta él, no la app.": "When you change it, iOS shows a one-time notice that the icon changed. That is normal, and it is iOS asking, not the app.",
        "Al volver a la app pide tu cara, tu huella o el código del teléfono.": "When you come back it asks for your face, fingerprint or phone passcode.",
        "Alimentación": "Food",
        "año": "year",
        "Apilada": "Stacked",
        "Aporte a {m}": "Contribution to {m}",
        "Aporte mensual": "Monthly contribution",
        "App de autenticación": "Authenticator app",
        "Aquí saldrá lo que anotes este mes.": "What you record this month will show up here.",
        "Así se pedirá cada vez que vuelvas a Chinola": "This is what you’ll see each time you come back to Chinola",
        "Así se verá": "This is how it will look",
        "Automático": "Automatic",
        "Automático sigue el modo claro u oscuro del teléfono.": "Automatic follows the phone’s light or dark mode.",
        "ayer": "yesterday",
        "Bajar": "Move down",
        "Bajaste": "You are down",
        "Balance del mes": "Monthly balance",
        "Banco": "Bank",
        "Banco (opcional)": "Bank (optional)",
        "Billetera": "Wallet",
        "Bloquear con Face ID": "Lock with Face ID",
        "Buscar movimiento…": "Search transactions…",
        "Buscar: tarjeta, PayPal, cripto…": "Search: card, PayPal, crypto…",
        "Cabecera": "Header",
        "Cambiar mi contraseña": "Change my password",
        "Cambiar mi correo": "Change my email",
        "Cancelar": "Cancel",
        "Categoría": "Category",
        "Cerrar": "Sign out",
        "Chinola está bloqueada": "Chinola is locked",
        "Claro": "Light",
        "Clásica": "Classic",
        "Código por correo": "Code by email",
        "Códigos de respaldo": "Backup codes",
        "Color": "Colour",
        "Color de la cabecera": "Header color",
        "Color de la tarjeta": "Card color",
        "Colores": "Colors",
        "Colores de las cifras": "Number colours",
        "Con centavos": "With cents",
        "Con Chino": "With Chino",
        "Con gráfica": "With a chart",
        "Con la verificación puesta, tu contraseña sola no abre la cuenta.": "With verification on, your password alone won’t open the account.",
        "Con las esquinas de abajo redondeadas, como una tarjeta": "With rounded bottom corners, like a card",
        "Copiado": "Copied",
        "Copiar": "Copy",
        "corte día {n}": "closes on the {n}th",
        "Cuál quieres en la pantalla de inicio": "Which one you want on your home screen",
        "Cuánto quieres gastar al mes en esta categoría. Déjalo en 0 para dejarla sin presupuesto.": "How much you want to spend a month in this category. Leave it at 0 for no budget.",
        "Cuentas": "Accounts",
        "cuentas − deudas": "accounts − debts",
        "Cuota": "Instalment",
        "de": "of",
        "De {a} a {b}": "From {a} to {b}",
        "De dónde sale": "Where it comes from",
        "Debes": "You owe",
        "déficit del mes": "deficit this month",
        "del exceso": "of the overage",
        "del límite": "of the limit",
        "del mes": "this month",
        "Del sistema": "System",
        "Del tema": "From the theme",
        "Desactivada": "Off",
        "Desbloquea Chinola para ver tus finanzas": "Unlock Chinola to see your finances",
        "Desbloquear": "Unlock",
        "Deuda actual": "Current debt",
        "Deuda y fechas": "Debt and dates",
        "Deudas": "Debts",
        "Día de corte": "Statement day",
        "Día de pago": "Due day",
        "días": "days",
        "Dinero": "Money",
        "disponible este mes": "available this month",
        "Donaciones": "Donations",
        "Dónde tienes la sesión abierta": "Where you are signed in",
        "Editar": "Edit",
        "Editar la pantalla": "Edit this screen",
        "Editar mi perfil": "Edit my profile",
        "Educación": "Education",
        "Efectivo": "Cash",
        "el de fábrica": "the default one",
        "El de la app": "The app’s own",
        "El icono de la app": "The app icon",
        "El presupuesto": "The budget",
        "El rótulo debajo de cada icono": "The label under each icon",
        "Eliminar": "Delete",
        "Eliminar mi cuenta": "Delete my account",
        "Empezar de nuevo": "Start over",
        "en": "in",
        "en {n} d": "in {n}d",
        "En aro": "As a ring",
        "En barra": "As a bar",
        "En bloques": "As blocks",
        "En qué fue": "What it was for",
        "En uso": "In use",
        "Enseñar el dinero": "Show the money",
        "Entidad o persona (opcional)": "Lender or person (optional)",
        "Entretenimiento": "Entertainment",
        "Entró": "Signed in",
        "Es lo que tendrías si hoy pagaras todas tus deudas.": "That is what you would have if you paid off everything today.",
        "Esquinas redondeadas": "Rounded corners",
        "este equipo": "this device",
        "este mes": "this month",
        "Este mes": "This month",
        "Este mes va corto: empieza por los gastos variables.": "This month is tight: start with variable expenses.",
        "Esto revierte su efecto en los saldos. No se puede deshacer.": "This undoes its effect on your balances. It cannot be undone.",
        "explica el": "accounts for",
        "explican el": "account for",
        "Fecha": "Date",
        "Fijo": "Fixed",
        "Fijos": "Fixed",
        "Gastado": "Spent",
        "Gastado en": "Spent in",
        "Gastado en el período": "Spent in this period",
        "Gastaste": "You spent",
        "Gastos": "Expenses",
        "Guardado, no para gastar mañana": "Put away, not to spend tomorrow",
        "Guardar": "Save",
        "Guardar archivo": "Save file",
        "Hablar con Chino": "Talk to Chino",
        "hace {n} días": "{n} days ago",
        "hace {n} h": "{n} h ago",
        "hace {n} min": "{n} min ago",
        "hace más de un mes": "over a month ago",
        "hace un momento": "just now",
        "Hacer {r}": "Make {r}",
        "hoy": "today",
        "Hoy": "Today",
        "Ibas a": "You were on",
        "Icono": "Icon",
        "Ingreso": "Income",
        "Ingresos": "Income",
        "Integrada": "Blended in",
        "Inversión": "Investment",
        "Invitar": "Invite",
        "Ir a organizar el panel": "Go organize the dashboard",
        "La suma": "The sum",
        "La tarjeta de arriba": "The card on top",
        "Las cifras del mes en tarjetas de su color, con más vida": "The month’s figures in cards of their own color, livelier",
        "Las pestañas": "The tabs",
        "Letra": "Typeface",
        "Letra de los títulos": "Heading typeface",
        "Letra del texto": "Body typeface",
        "Libretas y permisos": "Books & permissions",
        "Límite": "Limit",
        "Listo": "Done",
        "Lo que debes": "What you owe",
        "Lo que entra, lo que sale y lo que apartas. Hay una que se distingue con daltonismo.": "What comes in, what goes out and what you set aside. One of them works with colour blindness.",
        "Lo que entró, lo que salió y lo que te queda, de un vistazo.": "What came in, what went out and what is left, at a glance.",
        "Lo que tienes": "What you have",
        "Lo último que pasó": "What happened lately",
        "Los centavos": "Cents",
        "Mantén pulsada para mover · pellizca para el tamaño": "Hold to move · pinch to resize",
        "Mantén pulsada una tarjeta para moverla, pellizca para cambiar su tamaño, y en su menú la ocultas o la quitas.": "Press and hold a card to move it, pinch to resize it, and use its menu to hide or remove it.",
        "Menú de abajo": "Bottom menu",
        "Mes pasado": "Last month",
        "meses": "months",
        "Meta": "Goal",
        "Mi cuenta": "My account",
        "Mi plan": "My plan",
        "Miembros": "Members",
        "Modo": "Mode",
        "Moneda": "Currency",
        "Monto total": "Total amount",
        "Movimientos": "Transactions",
        "Movs.": "Trans.",
        "Nada con ese nombre": "Nothing by that name",
        "Ninguna": "None",
        "No": "No",
        "No disponible": "Not available",
        "No hay movimientos": "No transactions",
        "Nombre": "Name",
        "Nombre (ej. Cuenta principal)": "Name (e.g. Main account)",
        "Nombre (ej. Préstamo del carro)": "Name (e.g. Car loan)",
        "Nombre (ej. Visa Popular)": "Name (e.g. Visa Popular)",
        "Nombres en el menú": "Names in the menu",
        "Nueva cuenta": "New account",
        "Nueva libreta": "New book",
        "Nueva meta": "New goal",
        "Nueva tarjeta": "New card",
        "Nuevo préstamo": "New loan",
        "Objetivo": "Target",
        "Ocultar el dinero": "Hide the money",
        "Organiza tu panel": "Organize your dashboard",
        "Organizar el panel": "Organize the dashboard",
        "Oscuro": "Dark",
        "Otros": "Other",
        "Pagado con": "Paid with",
        "Pago": "Payment",
        "Pago de {p}": "Payment on {p}",
        "Panel del resumen": "Dashboard",
        "Para gastar": "To spend",
        "Para lo que pagas siempre: renta, luz, colegio": "For what you always pay: rent, power, school",
        "Pastillas": "Pills",
        "Patrimonio": "Net worth",
        "Perfil": "Profile",
        "Periodo": "Period",
        "Personal": "Personal",
        "Plan": "Plan",
        "por día": "a day",
        "Préstamos": "Loans",
        "Préstamos y fiados": "Loans and IOUs",
        "Presupuesto de {n}": "{n} budget",
        "Puedes tener varios a la vez y elegir con cuál entrar. Todos son gratis.": "You can have several at once and choose which one to use. All are free.",
        "Qué sabe hacer Chino": "What Chino can do",
        "Qué se ve arriba": "What shows at the top",
        "Quedan": "Left",
        "Quitar de la libreta": "Remove from the book",
        "Quitar del panel": "Remove from the dashboard",
        "Repetir cada mes": "Repeat every month",
        "Reportar un problema": "Report a problem",
        "Resumen": "Overview",
        "Saldo actual": "Current balance",
        "Salud": "Health",
        "Seguir en la web": "Continue on the web",
        "Seguridad": "Security",
        "Servicios": "Utilities",
        "Si hoy pagas todo, te quedan": "If you pay everything today, you keep",
        "Sin centavos": "No cents",
        "Sin color propio: la cabecera toma el fondo de la pantalla.": "No colour of its own: the header takes the screen’s background.",
        "Sin cuotas este mes: buen momento para aportar a tus metas.": "No installments this month: a good time to add to your goals.",
        "Sin nada con qué bloquear": "Nothing to lock with",
        "Subir": "Move up",
        "Subrayadas": "Underlined",
        "Tamaño de la letra": "Text size",
        "Tarjetas": "Cards",
        "tarjetas + préstamos": "cards + loans",
        "Tarjetas con color": "Colored cards",
        "Tarjetas y crédito": "Cards and credit",
        "Te deben": "Owed to you",
        "Te pasaste": "Over by",
        "Te pasaste por": "Over by",
        "Te queda": "You have left",
        "Te queda si pagas todo": "Left if you pay everything",
        "Tema de día": "Day theme",
        "Tema de noche": "Night theme",
        "Tendencia": "Trend",
        "Tienes": "You have",
        "Tipo": "Type",
        "todo": "all",
        "Todo": "All time",
        "Todos": "All",
        "Total": "Total",
        "Transferencia": "Transfer",
        "Transporte": "Transport",
        "tú": "you",
        "Tu límite": "Your limit",
        "Tu patrimonio este mes": "Your net worth this month",
        "Tu teléfono no tiene Face ID, huella ni código. Ponle uno en Ajustes y vuelve a encenderlo.": "Your phone has no Face ID, fingerprint or passcode. Set one in Settings and turn this on again.",
        "Tus cuotas fijas son {monto}, un {pct}% de tus ingresos.": "Your fixed instalments are {monto}, {pct}% of your income.",
        "Últimos 12 meses": "Last 12 months",
        "Últimos 3 meses": "Last 3 months",
        "Variable": "Variable",
        "Variables": "Variable",
        "Vas a": "You are on",
        "Ver detalle": "See details",
        "Ver la tendencia": "See the trend",
        "Verificación en dos pasos": "Two-step verification",
        "visto": "seen",
        "Vivienda": "Housing",
        "Volver": "Back",
        "y": "and",
        "Ya pagado": "Already paid"
    ]

    /// Español → francés.
    static let fr: [String: String] = [
        "¡Subiste": "Tu as gagné",
        "¿Cómo es?": "C’est quoi ?",
        "¿Eliminar movimiento?": "Supprimer l’opération ?",
        "¿Qué quieres agregar?": "Que quieres-tu ajouter ?",
        "{n} sin usar": "{n} non utilisés",
        "% de tus ingresos": "% de tes revenus",
        "A este ritmo llegas en": "À ce rythme tu y arrives en",
        "Abrir": "Ouvrir",
        "Activa al menos un método: al entrar te pediremos un código además de la contraseña.": "Active au moins une méthode : à la connexion on te demandera un code en plus du mot de passe.",
        "Activada": "Activée",
        "Activo": "Actif",
        "Agotado": "Épuisé",
        "Agregar tarjeta": "Ajouter une carte",
        "Ahora no": "Pas maintenant",
        "Ahorro": "Épargne",
        "Ahorro e inversión": "Épargne et placements",
        "Al cambiarlo, iOS avisa una vez de que el icono cambió. Es normal y lo pregunta él, no la app.": "En le changeant, iOS prévient une fois que l’icône a changé. C’est normal, et c’est lui qui le demande, pas l’app.",
        "Al volver a la app pide tu cara, tu huella o el código del teléfono.": "Au retour dans l’appli, il demande ton visage, ton empreinte ou le code du téléphone.",
        "Alimentación": "Alimentation",
        "año": "an",
        "Apilada": "Empilée",
        "Aporte a {m}": "Versement à {m}",
        "Aporte mensual": "Versement mensuel",
        "App de autenticación": "Appli d’authentification",
        "Aquí saldrá lo que anotes este mes.": "Ce que tu noteras ce mois-ci apparaîtra ici.",
        "Así se pedirá cada vez que vuelvas a Chinola": "C’est ce qui sera demandé à chaque retour dans Chinola",
        "Así se verá": "Voici le rendu",
        "Automático": "Automatique",
        "Automático sigue el modo claro u oscuro del teléfono.": "Automatique suit le mode clair ou sombre du téléphone.",
        "ayer": "hier",
        "Bajar": "Descendre",
        "Bajaste": "Tu as perdu",
        "Balance del mes": "Solde du mois",
        "Banco": "Banque",
        "Banco (opcional)": "Banque (facultatif)",
        "Billetera": "Portefeuille",
        "Bloquear con Face ID": "Verrouiller avec Face ID",
        "Buscar movimiento…": "Chercher une opération…",
        "Buscar: tarjeta, PayPal, cripto…": "Chercher : carte, PayPal, crypto…",
        "Cabecera": "En-tête",
        "Cambiar mi contraseña": "Changer mon mot de passe",
        "Cambiar mi correo": "Changer mon adresse",
        "Cancelar": "Annuler",
        "Categoría": "Catégorie",
        "Cerrar": "Déconnecter",
        "Chinola está bloqueada": "Chinola est verrouillée",
        "Claro": "Clair",
        "Clásica": "Classique",
        "Código por correo": "Code par mail",
        "Códigos de respaldo": "Codes de secours",
        "Color": "Couleur",
        "Color de la cabecera": "Couleur de l’en-tête",
        "Color de la tarjeta": "Couleur de la carte",
        "Colores": "Couleurs",
        "Colores de las cifras": "Couleurs des chiffres",
        "Con centavos": "Avec centimes",
        "Con Chino": "Avec Chino",
        "Con gráfica": "Avec graphique",
        "Con la verificación puesta, tu contraseña sola no abre la cuenta.": "Avec la vérification, ton mot de passe seul n’ouvre pas le compte.",
        "Con las esquinas de abajo redondeadas, como una tarjeta": "Avec les coins du bas arrondis, comme une carte",
        "Copiado": "Copié",
        "Copiar": "Copier",
        "corte día {n}": "relevé le {n}",
        "Cuál quieres en la pantalla de inicio": "Laquelle tu veux sur ton écran d’accueil",
        "Cuánto quieres gastar al mes en esta categoría. Déjalo en 0 para dejarla sin presupuesto.": "Combien tu veux dépenser par mois dans cette catégorie. Laisse 0 pour ne pas lui mettre de budget.",
        "Cuentas": "Comptes",
        "cuentas − deudas": "comptes − dettes",
        "Cuota": "Échéance",
        "de": "sur",
        "De {a} a {b}": "De {a} vers {b}",
        "De dónde sale": "D’où ça sort",
        "Debes": "Tu dois",
        "déficit del mes": "déficit du mois",
        "del exceso": "du dépassement",
        "del límite": "de la limite",
        "del mes": "du mois",
        "Del sistema": "Système",
        "Del tema": "Du thème",
        "Desactivada": "Désactivée",
        "Desbloquea Chinola para ver tus finanzas": "Déverrouille Chinola pour voir tes finances",
        "Desbloquear": "Déverrouiller",
        "Deuda actual": "Dette actuelle",
        "Deuda y fechas": "Dette et dates",
        "Deudas": "Dettes",
        "Día de corte": "Jour de relevé",
        "Día de pago": "Jour d’échéance",
        "días": "jours",
        "Dinero": "Argent",
        "disponible este mes": "disponible ce mois-ci",
        "Donaciones": "Dons",
        "Dónde tienes la sesión abierta": "Où tu es connecté",
        "Editar": "Modifier",
        "Editar la pantalla": "Modifier cet écran",
        "Editar mi perfil": "Modifier mon profil",
        "Educación": "Éducation",
        "Efectivo": "Espèces",
        "el de fábrica": "celle par défaut",
        "El de la app": "Celle de l’app",
        "El icono de la app": "L’icône de l’app",
        "El presupuesto": "Le budget",
        "El rótulo debajo de cada icono": "Le libellé sous chaque icône",
        "Eliminar": "Supprimer",
        "Eliminar mi cuenta": "Supprimer mon compte",
        "Empezar de nuevo": "Recommencer",
        "en": "en",
        "en {n} d": "dans {n} j",
        "En aro": "En anneau",
        "En barra": "En barre",
        "En bloques": "En blocs",
        "En qué fue": "C’était pour quoi",
        "En uso": "Utilisé",
        "Enseñar el dinero": "Afficher l’argent",
        "Entidad o persona (opcional)": "Organisme ou personne (facultatif)",
        "Entretenimiento": "Loisirs",
        "Entró": "Connecté",
        "Es lo que tendrías si hoy pagaras todas tus deudas.": "C’est ce que tu aurais si tu payais tout aujourd’hui.",
        "Esquinas redondeadas": "Coins arrondis",
        "este equipo": "cet appareil",
        "este mes": "ce mois-ci",
        "Este mes": "Ce mois-ci",
        "Este mes va corto: empieza por los gastos variables.": "Ce mois est serré : commence par les dépenses variables.",
        "Esto revierte su efecto en los saldos. No se puede deshacer.": "Cela annule son effet sur les soldes. C’est irréversible.",
        "explica el": "représente",
        "explican el": "représentent",
        "Fecha": "Date",
        "Fijo": "Fixe",
        "Fijos": "Fixes",
        "Gastado": "Dépensé",
        "Gastado en": "Dépensé en",
        "Gastado en el período": "Dépensé sur la période",
        "Gastaste": "Tu as dépensé",
        "Gastos": "Dépenses",
        "Guardado, no para gastar mañana": "Mis de côté, pas pour demain",
        "Guardar": "Enregistrer",
        "Guardar archivo": "Enregistrer le fichier",
        "Hablar con Chino": "Parler à Chino",
        "hace {n} días": "il y a {n} jours",
        "hace {n} h": "il y a {n} h",
        "hace {n} min": "il y a {n} min",
        "hace más de un mes": "il y a plus d’un mois",
        "hace un momento": "à l’instant",
        "Hacer {r}": "Passer en {r}",
        "hoy": "aujourd’hui",
        "Hoy": "Aujourd’hui",
        "Ibas a": "Tu étais à",
        "Icono": "Icône",
        "Ingreso": "Revenu",
        "Ingresos": "Revenus",
        "Integrada": "Intégré",
        "Inversión": "Investissement",
        "Invitar": "Inviter",
        "Ir a organizar el panel": "Organiser le tableau de bord",
        "La suma": "La somme",
        "La tarjeta de arriba": "La carte du haut",
        "Las cifras del mes en tarjetas de su color, con más vida": "Les chiffres du mois dans des cartes de leur couleur, plus vivantes",
        "Las pestañas": "Les onglets",
        "Letra": "Police",
        "Letra de los títulos": "Police des titres",
        "Letra del texto": "Police du texte",
        "Libretas y permisos": "Carnets et permissions",
        "Límite": "Plafond",
        "Listo": "Terminé",
        "Lo que debes": "Ce que tu dois",
        "Lo que entra, lo que sale y lo que apartas. Hay una que se distingue con daltonismo.": "Ce qui entre, ce qui sort et ce que tu mets de côté. L’une d’elles convient au daltonisme.",
        "Lo que entró, lo que salió y lo que te queda, de un vistazo.": "Ce qui est entré, ce qui est sorti et ce qui reste, d’un coup d’œil.",
        "Lo que tienes": "Ce que tu as",
        "Lo último que pasó": "Ce qui s’est passé",
        "Los centavos": "Les centimes",
        "Mantén pulsada para mover · pellizca para el tamaño": "Maintiens pour déplacer · pince pour la taille",
        "Mantén pulsada una tarjeta para moverla, pellizca para cambiar su tamaño, y en su menú la ocultas o la quitas.": "Maintiens une carte pour la déplacer, pince pour changer sa taille, et depuis son menu masque-la ou retire-la.",
        "Menú de abajo": "Menu du bas",
        "Mes pasado": "Le mois dernier",
        "meses": "mois",
        "Meta": "Objectif",
        "Mi cuenta": "Mon compte",
        "Mi plan": "Mon offre",
        "Miembros": "Membres",
        "Modo": "Mode",
        "Moneda": "Devise",
        "Monto total": "Montant total",
        "Movimientos": "Opérations",
        "Movs.": "Opér.",
        "Nada con ese nombre": "Rien à ce nom",
        "Ninguna": "Aucune",
        "No": "Non",
        "No disponible": "Indisponible",
        "No hay movimientos": "Aucune opération",
        "Nombre": "Nom",
        "Nombre (ej. Cuenta principal)": "Nom (ex. Compte principal)",
        "Nombre (ej. Préstamo del carro)": "Nom (ex. Prêt auto)",
        "Nombre (ej. Visa Popular)": "Nom (ex. Visa Popular)",
        "Nombres en el menú": "Noms dans le menu",
        "Nueva cuenta": "Nouveau compte",
        "Nueva libreta": "Nouveau carnet",
        "Nueva meta": "Nouvel objectif",
        "Nueva tarjeta": "Nouvelle carte",
        "Nuevo préstamo": "Nouveau prêt",
        "Objetivo": "Objectif",
        "Ocultar el dinero": "Masquer l’argent",
        "Organiza tu panel": "Organise ton tableau",
        "Organizar el panel": "Organiser le tableau",
        "Oscuro": "Sombre",
        "Otros": "Autres",
        "Pagado con": "Payé avec",
        "Pago": "Paiement",
        "Pago de {p}": "Paiement de {p}",
        "Panel del resumen": "Tableau de bord",
        "Para gastar": "À dépenser",
        "Para lo que pagas siempre: renta, luz, colegio": "Pour ce que tu paies toujours : loyer, électricité, école",
        "Pastillas": "Pastilles",
        "Patrimonio": "Patrimoine",
        "Perfil": "Profil",
        "Periodo": "Période",
        "Personal": "Personnel",
        "Plan": "Plan",
        "por día": "par jour",
        "Préstamos": "Prêts",
        "Préstamos y fiados": "Prêts et ardoises",
        "Presupuesto de {n}": "Budget de {n}",
        "Puedes tener varios a la vez y elegir con cuál entrar. Todos son gratis.": "Tu peux en avoir plusieurs et choisir avec laquelle entrer. Toutes sont gratuites.",
        "Qué sabe hacer Chino": "Ce que Chino sait faire",
        "Qué se ve arriba": "Ce qui s’affiche en haut",
        "Quedan": "Il reste",
        "Quitar de la libreta": "Retirer du carnet",
        "Quitar del panel": "Retirer du tableau",
        "Repetir cada mes": "Répéter chaque mois",
        "Reportar un problema": "Signaler un problème",
        "Resumen": "Résumé",
        "Saldo actual": "Solde actuel",
        "Salud": "Santé",
        "Seguir en la web": "Continuer sur le web",
        "Seguridad": "Sécurité",
        "Servicios": "Services",
        "Si hoy pagas todo, te quedan": "Si tu paies tout aujourd’hui, il te reste",
        "Sin centavos": "Sans centimes",
        "Sin color propio: la cabecera toma el fondo de la pantalla.": "Sans couleur propre : l’en-tête prend le fond de l’écran.",
        "Sin cuotas este mes: buen momento para aportar a tus metas.": "Pas de mensualités ce mois-ci : bon moment pour alimenter tes objectifs.",
        "Sin nada con qué bloquear": "Rien pour verrouiller",
        "Subir": "Monter",
        "Subrayadas": "Soulignés",
        "Tamaño de la letra": "Taille du texte",
        "Tarjetas": "Cartes",
        "tarjetas + préstamos": "cartes + prêts",
        "Tarjetas con color": "Cartes en couleur",
        "Tarjetas y crédito": "Cartes et crédit",
        "Te deben": "On te doit",
        "Te pasaste": "Dépassé de",
        "Te pasaste por": "Dépassé de",
        "Te queda": "Il te reste",
        "Te queda si pagas todo": "Il te reste si tu paies tout",
        "Tema de día": "Thème de jour",
        "Tema de noche": "Thème de nuit",
        "Tendencia": "Tendance",
        "Tienes": "Tu as",
        "Tipo": "Type",
        "todo": "tout",
        "Todo": "Tout",
        "Todos": "Tous",
        "Total": "Total",
        "Transferencia": "Virement",
        "Transporte": "Transport",
        "tú": "toi",
        "Tu límite": "Ta limite",
        "Tu patrimonio este mes": "Ton patrimoine ce mois-ci",
        "Tu teléfono no tiene Face ID, huella ni código. Ponle uno en Ajustes y vuelve a encenderlo.": "Ton téléphone n’a ni Face ID, ni empreinte, ni code. Ajoute-en un dans Réglages et réactive ceci.",
        "Tus cuotas fijas son {monto}, un {pct}% de tus ingresos.": "Tes mensualités fixes sont de {monto}, soit {pct}% de tes revenus.",
        "Últimos 12 meses": "12 derniers mois",
        "Últimos 3 meses": "3 derniers mois",
        "Variable": "Variable",
        "Variables": "Variables",
        "Vas a": "Tu es à",
        "Ver detalle": "Voir le détail",
        "Ver la tendencia": "Voir la tendance",
        "Verificación en dos pasos": "Vérification en deux étapes",
        "visto": "vu",
        "Vivienda": "Logement",
        "Volver": "Retour",
        "y": "et",
        "Ya pagado": "Déjà payé"
    ]

    /// La tabla de un idioma, o ninguna si es español —que es como están
    /// escritos los textos en el propio Swift—.
    static func de(_ idioma: String) -> [String: String] {
        switch idioma {
        case "en": return en
        case "fr": return fr
        default: return [:]
        }
    }
}
