// GENERADO por `npm run sync` desde el diccionario de la web — no editar a mano.
//
// Las traducciones de lo que va escrito dentro de las pantallas nativas.
// Las mandaba la web por el puente, así que el teléfono no sabía decir
// «Balance» en inglés hasta que la web arrancaba: al abrir la app, lo
// nativo salía en español un momento. Y el día que el webview se quite, se
// quedaba sin idioma.

import Foundation

enum CNTextosGenerados {

    /// Español → inglés.
    static let en: [String: String] = [
        "¡Sigue así!": "Keep it up!",
        "¡Subiste": "You are up",
        "¿Cómo es?": "What is it?",
        "¿Eliminar movimiento?": "Delete this transaction?",
        "¿Qué quieres agregar?": "What do you want to add?",
        "{n} al mes": "{n} a month",
        "{n} movimientos": "{n} transactions",
        "{n} movs": "{n} transactions",
        "{n} sin usar": "{n} unused",
        "{n}% de tus ingresos": "{n}% of your income",
        "% de tus ingresos": "% of your income",
        "◀ desliza para cancelar · ▲ para fijar": "◀ slide to cancel · ▲ to lock",
        "1 mov": "1 transaction",
        "A este ritmo llegas en": "At this pace you get there in",
        "a este ritmo, {n} al cierre": "at this pace, {n} by month end",
        "Abonar otro monto": "Pay another amount",
        "Abrir": "Open",
        "Acciones": "Shares",
        "Acerca de": "About",
        "Activa al menos un método: al entrar te pediremos un código además de la contraseña.": "Turn on at least one method: when signing in we’ll ask for a code besides your password.",
        "Activada": "On",
        "Activo": "On",
        "Activos": "Assets",
        "Administradora (opcional)": "Fund manager (optional)",
        "Agotado": "Used up",
        "Agregar tarjeta": "Add a card",
        "Agregar una tarjeta": "Add a card",
        "Ahora no": "Not now",
        "Ahorro": "Savings",
        "Ahorro e inversión": "Savings and investments",
        "Ahorro o certificado": "Savings or certificate",
        "Al cambiarlo, iOS avisa una vez de que el icono cambió. Es normal y lo pregunta él, no la app.": "When you change it, iOS shows a one-time notice that the icon changed. That is normal, and it is iOS asking, not the app.",
        "al día, {n} días por delante": "a day, {n} days to go",
        "al mes": "a month",
        "Al volver a la app pide tu cara, tu huella o el código del teléfono.": "When you come back it asks for your face, fingerprint or phone passcode.",
        "Alimentación": "Food",
        "Ancha": "Wide",
        "Ancho": "Width",
        "Anota algo hoy y arranca la racha": "Log something today to start a streak",
        "anotando seguido": "logging steadily",
        "Anotar": "Add",
        "Anotar un movimiento": "Add a transaction",
        "Anotar un movimiento en Chinola": "Add a transaction in Chinola",
        "anteayer": "the day before yesterday",
        "Antes del corte de una tarjeta o de la cuota de un préstamo.": "Before a card billing date or a loan instalment.",
        "año": "year",
        "apartado en {a}": "set aside in {a}",
        "Apilada": "Stacked",
        "Aplicar": "Apply",
        "Aportar a la meta": "Contribute to the goal",
        "Aporte a {m}": "Contribution to {m}",
        "Aporte mensual": "Monthly contribution",
        "App de autenticación": "Authenticator app",
        "Aquí saldrá lo que anotes este mes.": "What you record this month will show up here.",
        "Aquí saldrá todo lo que anotes con esta cuenta.": "Everything you record with this account will show up here.",
        "Aquí saldrá todo lo que pagues con esta tarjeta.": "Everything you pay with this card will show up here.",
        "Aquí saldrán los pagos que vayas anotando.": "The payments you add will show up here.",
        "así cerró el mes": "that is how the month closed",
        "Así se pedirá cada vez que vuelvas a Chinola": "This is what you’ll see each time you come back to Chinola",
        "Así se verá": "This is how it will look",
        "Automático": "Automatic",
        "Automático sigue el modo claro u oscuro del teléfono.": "Automatic follows the phone’s light or dark mode.",
        "Avisar de un problema": "Report a problem",
        "Avisos de pago": "Payment reminders",
        "ayer": "yesterday",
        "Ayer": "Yesterday",
        "Ayer gastaste": "You spent yesterday",
        "Bajar": "Move down",
        "Bajaste": "You are down",
        "Balance del mes": "Monthly balance",
        "Banco": "Bank",
        "Banco (opcional)": "Bank (optional)",
        "Bienes raíces": "Real estate",
        "Billetera": "Wallet",
        "Billetera digital": "Digital wallet",
        "Bitcoin, USDT y otras": "Bitcoin, USDT and others",
        "Bloquear con Face ID": "Lock with Face ID",
        "Buscar": "Search",
        "Buscar movimiento…": "Search transactions…",
        "Buscar: tarjeta, PayPal, cripto…": "Search: card, PayPal, crypto…",
        "Cabecera": "Header",
        "Cambiar mi contraseña": "Change my password",
        "Cambiar mi correo": "Change my email",
        "Cancelar": "Cancel",
        "Casa de bolsa o app": "Brokerage or app",
        "Casa, solar o apartamento": "A house, a plot or a flat",
        "Categoría": "Category",
        "Centro (opcional)": "School (optional)",
        "Cerrar": "Sign out",
        "Chica": "Small",
        "Chino": "Chino",
        "Chinola está bloqueada": "Chinola is locked",
        "Chinola no pudo arrancar": "Chinola could not start",
        "Claro": "Light",
        "Clásica": "Classic",
        "Código": "Code",
        "Código por correo": "Code by email",
        "Códigos de respaldo": "Backup codes",
        "Color": "Colour",
        "Color de la cabecera": "Header color",
        "Color de la tarjeta": "Card color",
        "Colores": "Colors",
        "Colores de las cifras": "Number colours",
        "Comedor o cafetería": "Canteen or cafeteria",
        "Cómo ha ido el patrimonio": "How net worth has gone",
        "Como la cabecera": "Like the header",
        "Cómo se ve": "How it looks",
        "Cómo se ven tus cuentas": "How your accounts look",
        "Cómo te fue el mes, cuando se acaba.": "How your month went, once it ends.",
        "Cómoda": "Comfortable",
        "Compacta": "Compact",
        "Con centavos": "With cents",
        "Con Chino": "With Chino",
        "Con gráfica": "With a chart",
        "Con la verificación puesta, tu contraseña sola no abre la cuenta.": "With verification on, your password alone won’t open the account.",
        "Con las esquinas de abajo redondeadas, como una tarjeta": "With rounded bottom corners, like a card",
        "Con límite, día de corte y día de pago": "With a limit, a billing date and a payment date",
        "Con qué": "With what",
        "Concepto": "Description",
        "Consumos con esta tarjeta": "Spending on this card",
        "Copiado": "Copied",
        "Copiar": "Copy",
        "Corriente o nómina, con tarjeta de débito": "Checking or payroll, with a debit card",
        "corte día {n}": "closes on the {n}th",
        "crédito": "credit",
        "Criptomonedas": "Cryptocurrencies",
        "Cuál quieres en la pantalla de inicio": "Which one you want on your home screen",
        "Cualquier tarjeta que recargas": "Any card you top up",
        "Cuando Chino tiene algo que decirte de tus números.": "When Chino has something to tell you about your numbers.",
        "Cuánto cargas": "How much you carry",
        "Cuánto quieres gastar al mes en esta categoría. Déjalo en 0 para dejarla sin presupuesto.": "How much you want to spend a month in this category. Leave it at 0 for no budget.",
        "Cuánto tienes guardado": "How much you have put away",
        "Cuánto vale hoy": "What it is worth today",
        "Cuenta": "Account",
        "Cuenta de banco": "Bank account",
        "cuenta de miembro": "member account",
        "Cuentas": "Accounts",
        "cuentas − deudas": "accounts − debts",
        "Cuota": "Instalment",
        "Cuota mensual": "Monthly instalment",
        "Cuotas restantes": "Instalments left",
        "de": "of",
        "De {a} a {b}": "From {a} to {b}",
        "De dónde sale": "Where it comes from",
        "de tus gastos es fijo · {n} variable": "of your spending is fixed · {n} variable",
        "Debes": "You owe",
        "Debes ahora": "You owe now",
        "débito": "debit",
        "déficit del mes": "deficit this month",
        "Degradado": "Gradient",
        "del exceso": "of the overage",
        "del límite": "of the limit",
        "del mes": "this month",
        "Del sistema": "System",
        "Del tema": "From the theme",
        "Desactivada": "Off",
        "Desbloquea Chinola para ver tus finanzas": "Unlock Chinola to see your finances",
        "Desbloquear": "Unlock",
        "Deshacer": "Undo",
        "Deuda actual": "Current debt",
        "Deuda y fechas": "Debt and dates",
        "Deudas": "Debts",
        "día": "day",
        "día {d}": "day {d}",
        "Día de corte": "Statement day",
        "Día de pago": "Due day",
        "días": "days",
        "Dictar": "Dictate",
        "Dime qué gastaste": "Tell me what you spent",
        "Dinero": "Money",
        "Dinero del banco que usas y repones": "Money from the bank that you use and pay back",
        "Dinero guardado que no tocas": "Money put away that you do not touch",
        "Disponible": "Available",
        "disponible este mes": "available this month",
        "Donaciones": "Donations",
        "Dónde es (ej. el gimnasio)": "Where it is (e.g. the gym)",
        "Dónde está (opcional)": "Where it is (optional)",
        "Dónde está tu dinero": "Where your money is",
        "Dónde la tienes (ej. Binance)": "Where you keep it (e.g. Binance)",
        "Dónde lo guardas (opcional)": "Where you keep it (optional)",
        "Dónde se usa (opcional)": "Where it is used (optional)",
        "Dónde tienes la sesión abierta": "Where you are signed in",
        "Editar": "Edit",
        "Editar cuenta": "Edit account",
        "Editar la pantalla": "Edit this screen",
        "Editar mi perfil": "Edit my profile",
        "Editar movimiento": "Edit transaction",
        "Editar préstamo": "Edit loan",
        "Editar tarjeta": "Edit card",
        "Educación": "Education",
        "Efectivo": "Cash",
        "el de fábrica": "the default one",
        "El de la app": "The app’s own",
        "El dictado no está disponible ahora mismo.": "Dictation is not available right now.",
        "El icono de la app": "The app icon",
        "el mes pasado no hubo gastos": "no expenses last month",
        "El micrófono lo está usando otra app. Ciérrala y vuelve a intentarlo.": "Another app is using the microphone. Close it and try again.",
        "El presupuesto": "The budget",
        "El rótulo debajo de cada icono": "The label under each icon",
        "El tuyo ahora": "Yours right now",
        "Eliminar": "Delete",
        "Eliminar mi cuenta": "Delete my account",
        "Empezar": "Get started",
        "Empezar de nuevo": "Start over",
        "en": "in",
        "en {n} d": "in {n}d",
        "En aro": "As a ring",
        "En barra": "As a bar",
        "En bloques": "As blocks",
        "En esa cuenta hay {h}. No alcanza para apartar {c}.": "That account has {h}. Not enough to set aside {c}.",
        "En esa cuenta hay {h}. No alcanza para pagar {c}.": "That account has {h}. Not enough to pay {c}.",
        "En qué fue": "What it was for",
        "En una casa de bolsa o app": "At a brokerage or in an app",
        "En uso": "In use",
        "Enseñar": "Show",
        "Enseñar el dinero": "Show the money",
        "Enseñar la tendencia": "Show the trend",
        "Entendido": "Got it",
        "Entidad o persona (opcional)": "Lender or person (optional)",
        "Entretenimiento": "Entertainment",
        "Entró": "In",
        "Entró este mes": "Came in this month",
        "Enviar": "Send",
        "Es lo que tendrías si hoy pagaras todas tus deudas.": "That is what you would have if you paid off everything today.",
        "Esconder las cifras": "Hide the figures",
        "Ese préstamo ya está pagado.": "That loan is already paid off.",
        "Esquinas redondeadas": "Rounded corners",
        "este equipo": "this device",
        "este mes": "this month",
        "Este mes": "This month",
        "Este mes va corto: empieza por los gastos variables.": "This month is tight: start with variable expenses.",
        "Este teléfono no la trae. Chino sigue funcionando con la IA de Chinola.": "This phone does not have it. Chino keeps working with Chinola’s AI.",
        "Esto no se puede deshacer.": "This cannot be undone.",
        "Esto revierte su efecto en los saldos. No se puede deshacer.": "This undoes its effect on your balances. It cannot be undone.",
        "explica el": "accounts for",
        "explican el": "account for",
        "Fecha": "Date",
        "Fijo": "Fixed",
        "Fijos": "Fixed",
        "Fondo de inversión": "Investment fund",
        "Fondos mutuos o de pensión voluntaria": "Mutual or voluntary pension funds",
        "Gastado": "Spent",
        "Gastado en": "Spent in",
        "Gastado en el período": "Spent in this period",
        "gastas {n}% más que el mes pasado": "you spend {n}% more than last month",
        "gastas {n}% menos que el mes pasado": "you spend {n}% less than last month",
        "Gastaste": "You spent",
        "Gasto": "Expense",
        "Gasto con ella": "Spend with it",
        "Gastos": "Expenses",
        "Gimnasio, club, supermercado": "Gym, club, supermarket",
        "Gráfica": "Chart",
        "Guardado, no para gastar mañana": "Put away, not to spend tomorrow",
        "Guardar": "Save",
        "Guardar archivo": "Save file",
        "Hablar con Chino": "Talk to Chino",
        "hace {n} días": "{n} days ago",
        "hace {n} h": "{n} h ago",
        "hace {n} min": "{n} min ago",
        "Hace falta tu permiso para dictar.": "Dictation needs your permission.",
        "Hace falta tu permiso para usar el micrófono.": "The microphone needs your permission.",
        "hace más de un mes": "over a month ago",
        "hace un momento": "just now",
        "Hacer {r}": "Make {r}",
        "hoy": "today",
        "Hoy": "Today",
        "Ibas a": "You were on",
        "Icono": "Icon",
        "Ingreso": "Income",
        "Ingresos": "Income",
        "Integrada": "Blended in",
        "Inversión": "Investment",
        "invierte": "invest",
        "Invitar": "Invite",
        "Ir a organizar el panel": "Go organize the dashboard",
        "La forma de la tarjeta y lo apretada que va la lista. Son de este teléfono, no de la libreta.": "The card shape and how tight the list is. They belong to this phone, not to the book.",
        "La suma": "The sum",
        "La tarjeta de arriba": "The card on top",
        "Las cifras del mes en tarjetas de su color, con más vida": "The month’s figures in cards of their own color, livelier",
        "Las pestañas": "The tabs",
        "Letra": "Typeface",
        "Letra de los títulos": "Heading typeface",
        "Letra del texto": "Body typeface",
        "Libretas y permisos": "Books & permissions",
        "Límite": "Limit",
        "Línea de crédito": "Line of credit",
        "Lisa": "Flat",
        "Lista. Lo que le preguntes no sale de este teléfono.": "Ready. What you ask it never leaves this phone.",
        "Listo": "Done",
        "Lo que cargas en la cartera": "What you carry in your wallet",
        "Lo que debes": "What you owe",
        "Lo que entra, lo que sale y lo que apartas. Hay una que se distingue con daltonismo.": "What comes in, what goes out and what you set aside. One of them works with colour blindness.",
        "Lo que entró, lo que salió y lo que te queda, de un vistazo.": "What came in, what went out and what is left, at a glance.",
        "Lo que le prestaste a un amigo o familiar": "What you lent to a friend or a relative",
        "Lo que tienes": "What you have",
        "Lo último que pasó": "What happened lately",
        "Los centavos": "Cents",
        "Mantén pulsada para mover · pellizca para el tamaño": "Hold to move · pinch to resize",
        "Mantén pulsada una tarjeta para moverla, pellizca para cambiar su tamaño, y en su menú la ocultas o la quitas.": "Press and hold a card to move it, pinch to resize it, and use its menu to hide or remove it.",
        "Mantén pulsada una tarjeta para su menú. Se mueve con las flechas y se estira con el ancho.": "Press and hold a card for its menu. Move it with the arrows and stretch it with the width.",
        "Mantén pulsado para hablar": "Hold to talk",
        "Marca un movimiento como «se repite cada mes»": "Mark a transaction as «repeats every month»",
        "Me deben": "They owe me",
        "Media": "Medium",
        "Membresía": "Membership",
        "Menú de abajo": "Bottom menu",
        "Mes pasado": "Last month",
        "meses": "months",
        "Meta": "Goal",
        "Metales": "Metals",
        "Metro, OMSA, peaje": "Metro, bus, tolls",
        "Mi cuenta": "My account",
        "Mi plan": "My plan",
        "Miembros": "Members",
        "Modo": "Mode",
        "Moneda": "Currency",
        "Monto total": "Total amount",
        "Movimientos": "Transactions",
        "Movimientos de esta cuenta": "Transactions in this account",
        "Movs.": "Trans.",
        "Nada con ese nombre": "Nothing by that name",
        "Nada por pagar": "Nothing to pay",
        "Nada que se repita": "Nothing repeating",
        "Ninguna": "None",
        "No": "No",
        "No disponible": "Not available",
        "No encuentro esa meta.": "I cannot find that goal.",
        "No encuentro esa tarjeta.": "I cannot find that card.",
        "No encuentro ese préstamo.": "I cannot find that loan.",
        "No hay movimientos": "No transactions",
        "No hay nada del año pasado": "Nothing from last year",
        "No se pudo abrir el selector": "Could not open the file picker",
        "No se pudo encender el micrófono.": "The microphone could not be turned on.",
        "No se pudo leer ese archivo": "Could not read that file",
        "Nombre": "Name",
        "Nombre (ej. Cuenta principal)": "Name (e.g. Main account)",
        "Nombre (ej. Préstamo del carro)": "Name (e.g. Car loan)",
        "Nombre (ej. Visa Popular)": "Name (e.g. Visa Popular)",
        "Nombres en el menú": "Names in the menu",
        "Nueva cuenta": "New account",
        "Nueva libreta": "New book",
        "Nueva meta": "New goal",
        "Nueva tarjeta": "New card",
        "Nuevo movimiento": "New transaction",
        "Nuevo préstamo": "New loan",
        "Objetivo": "Target",
        "Oculta": "Hidden",
        "Ocultar": "Hide",
        "Ocultar el dinero": "Hide the money",
        "Operador (ej. Metro)": "Operator (e.g. Metro)",
        "Organiza tu panel": "Organize your dashboard",
        "Organizar el panel": "Organize the dashboard",
        "Oro o plata": "Gold or silver",
        "Oscuro": "Dark",
        "Otra con saldo": "Another one with a balance",
        "Otros": "Other",
        "Pagado": "Paid",
        "Pagado con": "Paid with",
        "Pagar la tarjeta": "Pay the card",
        "Pago": "Payment",
        "Pago de {p}": "Payment on {p}",
        "pago en {n} d": "due in {n} d",
        "Pagos registrados": "Payments recorded",
        "Panel del resumen": "Dashboard",
        "Para gastar": "To spend",
        "Para lo que pagas siempre: renta, luz, colegio": "For what you always pay: rent, power, school",
        "Para mirar el teléfono en la calle": "For looking at your phone in the street",
        "Parar": "Stop",
        "Pasivos": "Liabilities",
        "Pastillas": "Pills",
        "Patrimonio": "Net worth",
        "PayPal, tPago, Qik…": "PayPal, tPago, Qik…",
        "pedir prestado / prestar": "borrow / lend",
        "Perfil": "Profile",
        "Periodo": "Period",
        "Personal": "Personal",
        "Plan": "Plan",
        "Pon cuánto vas a aportar.": "Enter how much you are putting in.",
        "Pon cuánto vas a pagar.": "Enter how much you are paying.",
        "Pon un presupuesto y te lo reparto": "Set a budget and I will split it for you",
        "Ponle presupuesto a tus categorías": "Set a budget on your categories",
        "por día": "a day",
        "Preguntarle a Chino": "Ask Chino",
        "Prepago y membresías": "Prepaid and memberships",
        "Préstamo del banco, del carro o de alguien": "A loan from the bank, for the car, or from someone",
        "Préstamos": "Loans",
        "Préstamos y fiados": "Loans and IOUs",
        "préstamos y tarjetas": "loans and cards",
        "Presupuesto de {n}": "{n} budget",
        "Probar otro método": "Try another way",
        "promedio del mes": "monthly average",
        "Prueba con un archivo de Chinola (.json) o un CSV del banco.": "Try a Chinola file (.json) or a bank CSV.",
        "Puedes tener varios a la vez y elegir con cuál entrar. Todos son gratis.": "You can have several at once and choose which one to use. All are free.",
        "que en el mismo mes de {a}": "than the same month of {a}",
        "Qué grupos se ven": "Which groups show",
        "Qué periodo miras": "Which period you are looking at",
        "Qué sabe hacer Chino": "What Chino can do",
        "Qué se ve arriba": "What shows at the top",
        "Quedan": "Left",
        "Quitar": "Remove",
        "Quitar de la libreta": "Remove from the book",
        "Quitar del panel": "Remove from the dashboard",
        "Rango": "Range",
        "Registrar abono": "Record a payment",
        "Registrar cuota": "Log a payment",
        "Registrar pago": "Record a payment",
        "Repetir cada mes": "Repeat every month",
        "Reportar un problema": "Report a problem",
        "Resumen": "Overview",
        "Resumen del mes": "Month summary",
        "Saldo actual": "Current balance",
        "Saldo de la tarjeta": "Card balance",
        "Saldo disponible": "Available balance",
        "Saldo o puntos": "Balance or points",
        "Salió este mes": "Went out this month",
        "Salud": "Health",
        "seguidos sin gastar": "in a row without spending",
        "Seguridad": "Security",
        "Servicio (ej. PayPal)": "Service (e.g. PayPal)",
        "Servicios": "Utilities",
        "Si hoy pagas todo, te quedan": "If you pay everything today, you keep",
        "si sigues gastando igual": "if you keep spending the same",
        "Sin banco": "No bank",
        "Sin centavos": "No cents",
        "Sin color propio: la cabecera toma el fondo de la pantalla.": "No colour of its own: the header takes the screen’s background.",
        "Sin cuotas este mes: buen momento para aportar a tus metas.": "No installments this month: a good time to add to your goals.",
        "Sin gastos este mes": "No spending this month",
        "Sin nada con qué bloquear": "Nothing to lock with",
        "Solo en Android": "Android only",
        "Subir": "Move up",
        "Subrayadas": "Underlined",
        "Suelta para cancelar": "Release to cancel",
        "Tamaño de la letra": "Text size",
        "Tarjeta de crédito": "Credit card",
        "Tarjeta de transporte": "Transport card",
        "Tarjeta escolar": "School card",
        "Tarjetas": "Cards",
        "tarjetas + préstamos": "cards + loans",
        "Tarjetas con color": "Colored cards",
        "Tarjetas de crédito": "Credit cards",
        "Tarjetas y crédito": "Cards and credit",
        "Te deben": "Owed to you",
        "Te escucho…": "Listening…",
        "Te falta cobrar": "Left to collect",
        "Te falta pagar": "Left to pay",
        "Te pasaste": "Over by",
        "Te pasaste por": "Over by",
        "Te queda": "You have left",
        "te queda este mes": "left this month",
        "Te queda si pagas todo": "Left if you pay everything",
        "Tema de día": "Day theme",
        "Tema de noche": "Night theme",
        "Tendencia": "Trend",
        "Tienes": "You have",
        "Tipo": "Type",
        "Toca el botón para terminar": "Tap the button to finish",
        "todo": "all",
        "Todo": "All time",
        "Todo el saldo": "The whole balance",
        "Todos": "All",
        "Total": "Total",
        "Transferencia": "Transfer",
        "Transferir": "Transfer",
        "Transporte": "Transport",
        "tú": "you",
        "Tu límite": "Your limit",
        "Tu patrimonio este mes": "Your net worth this month",
        "Tu teléfono no tiene Face ID, huella ni código. Ponle uno en Ajustes y vuelve a encenderlo.": "Your phone has no Face ID, fingerprint or passcode. Set one in Settings and turn this on again.",
        "Tu teléfono puede, pero hay que bajarla primero.": "Your phone can, but it has to be downloaded first.",
        "Tus cuotas fijas son {monto}, un {pct}% de tus ingresos.": "Your fixed instalments are {monto}, {pct}% of your income.",
        "Últimos 12 meses": "Last 12 months",
        "Últimos 3 meses": "Last 3 months",
        "Un momento…": "One moment…",
        "Variable": "Variable",
        "Variables": "Variable",
        "Vas a": "You are on",
        "Ver detalle": "See details",
        "Ver el presupuesto": "See the budget",
        "Ver la tendencia": "See the trend",
        "Ver más": "See more",
        "Verificación en dos pasos": "Two-step verification",
        "Vidrio": "Glass",
        "visto": "seen",
        "Vivienda": "Housing",
        "Volver": "Back",
        "Volver a intentarlo": "Try again",
        "y": "and",
        "Ya lo pagué": "Already paid it",
        "Ya pagado": "Already paid",
        "Ya pasaste el presupuesto del mes": "You are past this month’s budget",
        "Yo debo": "I owe"
    ]

    /// Español → francés.
    static let fr: [String: String] = [
        "¡Sigue así!": "Continue comme ça !",
        "¡Subiste": "Tu as gagné",
        "¿Cómo es?": "C’est quoi ?",
        "¿Eliminar movimiento?": "Supprimer l’opération ?",
        "¿Qué quieres agregar?": "Que quieres-tu ajouter ?",
        "{n} al mes": "{n} par mois",
        "{n} movimientos": "{n} opérations",
        "{n} movs": "{n} opérations",
        "{n} sin usar": "{n} non utilisés",
        "{n}% de tus ingresos": "{n} % de tes revenus",
        "% de tus ingresos": "% de tes revenus",
        "◀ desliza para cancelar · ▲ para fijar": "◀ glisse pour annuler · ▲ pour verrouiller",
        "1 mov": "1 opération",
        "A este ritmo llegas en": "À ce rythme tu y arrives en",
        "a este ritmo, {n} al cierre": "à ce rythme, {n} en fin de mois",
        "Abonar otro monto": "Verser un autre montant",
        "Abrir": "Ouvrir",
        "Acciones": "Actions",
        "Acerca de": "À propos",
        "Activa al menos un método: al entrar te pediremos un código además de la contraseña.": "Active au moins une méthode : à la connexion on te demandera un code en plus du mot de passe.",
        "Activada": "Activée",
        "Activo": "Actif",
        "Activos": "Actifs",
        "Administradora (opcional)": "Gestionnaire (facultatif)",
        "Agotado": "Épuisé",
        "Agregar tarjeta": "Ajouter une carte",
        "Agregar una tarjeta": "Ajouter une carte",
        "Ahora no": "Pas maintenant",
        "Ahorro": "Épargne",
        "Ahorro e inversión": "Épargne et placements",
        "Ahorro o certificado": "Épargne ou certificat",
        "Al cambiarlo, iOS avisa una vez de que el icono cambió. Es normal y lo pregunta él, no la app.": "En le changeant, iOS prévient une fois que l’icône a changé. C’est normal, et c’est lui qui le demande, pas l’app.",
        "al día, {n} días por delante": "par jour, {n} jours restants",
        "al mes": "par mois",
        "Al volver a la app pide tu cara, tu huella o el código del teléfono.": "Au retour dans l’appli, il demande ton visage, ton empreinte ou le code du téléphone.",
        "Alimentación": "Alimentation",
        "Ancha": "Large",
        "Ancho": "Largeur",
        "Anota algo hoy y arranca la racha": "Enregistre quelque chose aujourd’hui pour lancer la série",
        "anotando seguido": "tu enregistres régulièrement",
        "Anotar": "Noter",
        "Anotar un movimiento": "Noter une opération",
        "Anotar un movimiento en Chinola": "Noter une opération dans Chinola",
        "anteayer": "avant-hier",
        "Antes del corte de una tarjeta o de la cuota de un préstamo.": "Avant la date de facturation d’une carte ou l’échéance d’un prêt.",
        "año": "an",
        "apartado en {a}": "mis de côté en {a}",
        "Apilada": "Empilée",
        "Aplicar": "Appliquer",
        "Aportar a la meta": "Verser à l’objectif",
        "Aporte a {m}": "Versement à {m}",
        "Aporte mensual": "Versement mensuel",
        "App de autenticación": "Appli d’authentification",
        "Aquí saldrá lo que anotes este mes.": "Ce que tu noteras ce mois-ci apparaîtra ici.",
        "Aquí saldrá todo lo que anotes con esta cuenta.": "Tout ce que tu noteras avec ce compte apparaîtra ici.",
        "Aquí saldrá todo lo que pagues con esta tarjeta.": "Tout ce que tu paies avec cette carte apparaîtra ici.",
        "Aquí saldrán los pagos que vayas anotando.": "Les paiements que tu notes apparaîtront ici.",
        "así cerró el mes": "c’est ainsi que le mois s’est terminé",
        "Así se pedirá cada vez que vuelvas a Chinola": "C’est ce qui sera demandé à chaque retour dans Chinola",
        "Así se verá": "Voici le rendu",
        "Automático": "Automatique",
        "Automático sigue el modo claro u oscuro del teléfono.": "Automatique suit le mode clair ou sombre du téléphone.",
        "Avisar de un problema": "Signaler un problème",
        "Avisos de pago": "Rappels de paiement",
        "ayer": "hier",
        "Ayer": "Hier",
        "Ayer gastaste": "Tu as dépensé hier",
        "Bajar": "Descendre",
        "Bajaste": "Tu as perdu",
        "Balance del mes": "Solde du mois",
        "Banco": "Banque",
        "Banco (opcional)": "Banque (facultatif)",
        "Bienes raíces": "Immobilier",
        "Billetera": "Portefeuille",
        "Billetera digital": "Portefeuille numérique",
        "Bitcoin, USDT y otras": "Bitcoin, USDT et d’autres",
        "Bloquear con Face ID": "Verrouiller avec Face ID",
        "Buscar": "Rechercher",
        "Buscar movimiento…": "Chercher une opération…",
        "Buscar: tarjeta, PayPal, cripto…": "Chercher : carte, PayPal, crypto…",
        "Cabecera": "En-tête",
        "Cambiar mi contraseña": "Changer mon mot de passe",
        "Cambiar mi correo": "Changer mon adresse",
        "Cancelar": "Annuler",
        "Casa de bolsa o app": "Courtier ou app",
        "Casa, solar o apartamento": "Une maison, un terrain ou un appartement",
        "Categoría": "Catégorie",
        "Centro (opcional)": "Établissement (facultatif)",
        "Cerrar": "Déconnecter",
        "Chica": "Petite",
        "Chino": "Chino",
        "Chinola está bloqueada": "Chinola est verrouillée",
        "Chinola no pudo arrancar": "Chinola n’a pas pu démarrer",
        "Claro": "Clair",
        "Clásica": "Classique",
        "Código": "Code",
        "Código por correo": "Code par mail",
        "Códigos de respaldo": "Codes de secours",
        "Color": "Couleur",
        "Color de la cabecera": "Couleur de l’en-tête",
        "Color de la tarjeta": "Couleur de la carte",
        "Colores": "Couleurs",
        "Colores de las cifras": "Couleurs des chiffres",
        "Comedor o cafetería": "Cantine ou cafétéria",
        "Cómo ha ido el patrimonio": "Comment le patrimoine a évolué",
        "Como la cabecera": "Comme l’en-tête",
        "Cómo se ve": "Comment il s’affiche",
        "Cómo se ven tus cuentas": "Comment tes comptes s’affichent",
        "Cómo te fue el mes, cuando se acaba.": "Comment s’est passé ton mois, une fois fini.",
        "Cómoda": "Confortable",
        "Compacta": "Compacte",
        "Con centavos": "Avec centimes",
        "Con Chino": "Avec Chino",
        "Con gráfica": "Avec graphique",
        "Con la verificación puesta, tu contraseña sola no abre la cuenta.": "Avec la vérification, ton mot de passe seul n’ouvre pas le compte.",
        "Con las esquinas de abajo redondeadas, como una tarjeta": "Avec les coins du bas arrondis, comme une carte",
        "Con límite, día de corte y día de pago": "Avec un plafond, une date de facturation et une date de paiement",
        "Con qué": "Avec quoi",
        "Concepto": "Libellé",
        "Consumos con esta tarjeta": "Dépenses sur cette carte",
        "Copiado": "Copié",
        "Copiar": "Copier",
        "Corriente o nómina, con tarjeta de débito": "Compte courant ou salaire, avec carte de débit",
        "corte día {n}": "relevé le {n}",
        "crédito": "crédit",
        "Criptomonedas": "Cryptomonnaies",
        "Cuál quieres en la pantalla de inicio": "Laquelle tu veux sur ton écran d’accueil",
        "Cualquier tarjeta que recargas": "Toute carte que tu recharges",
        "Cuando Chino tiene algo que decirte de tus números.": "Quand Chino a quelque chose à te dire sur tes chiffres.",
        "Cuánto cargas": "Combien tu portes",
        "Cuánto quieres gastar al mes en esta categoría. Déjalo en 0 para dejarla sin presupuesto.": "Combien tu veux dépenser par mois dans cette catégorie. Laisse 0 pour ne pas lui mettre de budget.",
        "Cuánto tienes guardado": "Combien tu as mis de côté",
        "Cuánto vale hoy": "Combien ça vaut aujourd’hui",
        "Cuenta": "Compte",
        "Cuenta de banco": "Compte bancaire",
        "cuenta de miembro": "compte de membre",
        "Cuentas": "Comptes",
        "cuentas − deudas": "comptes − dettes",
        "Cuota": "Échéance",
        "Cuota mensual": "Mensualité",
        "Cuotas restantes": "Échéances restantes",
        "de": "sur",
        "De {a} a {b}": "De {a} vers {b}",
        "De dónde sale": "D’où ça sort",
        "de tus gastos es fijo · {n} variable": "de tes dépenses est fixe · {n} variable",
        "Debes": "Tu dois",
        "Debes ahora": "Tu dois maintenant",
        "débito": "débit",
        "déficit del mes": "déficit du mois",
        "Degradado": "Dégradé",
        "del exceso": "du dépassement",
        "del límite": "de la limite",
        "del mes": "du mois",
        "Del sistema": "Système",
        "Del tema": "Du thème",
        "Desactivada": "Désactivée",
        "Desbloquea Chinola para ver tus finanzas": "Déverrouille Chinola pour voir tes finances",
        "Desbloquear": "Déverrouiller",
        "Deshacer": "Annuler",
        "Deuda actual": "Dette actuelle",
        "Deuda y fechas": "Dette et dates",
        "Deudas": "Dettes",
        "día": "jour",
        "día {d}": "le {d}",
        "Día de corte": "Jour de relevé",
        "Día de pago": "Jour d’échéance",
        "días": "jours",
        "Dictar": "Dicter",
        "Dime qué gastaste": "Dis-moi ce que tu as dépensé",
        "Dinero": "Argent",
        "Dinero del banco que usas y repones": "De l’argent de la banque que tu utilises et rembourses",
        "Dinero guardado que no tocas": "De l’argent mis de côté que tu ne touches pas",
        "Disponible": "Disponible",
        "disponible este mes": "disponible ce mois-ci",
        "Donaciones": "Dons",
        "Dónde es (ej. el gimnasio)": "Où c’est (ex. la salle de sport)",
        "Dónde está (opcional)": "Où c’est (facultatif)",
        "Dónde está tu dinero": "Où est ton argent",
        "Dónde la tienes (ej. Binance)": "Où tu la gardes (ex. Binance)",
        "Dónde lo guardas (opcional)": "Où tu le gardes (facultatif)",
        "Dónde se usa (opcional)": "Où elle sert (facultatif)",
        "Dónde tienes la sesión abierta": "Où tu es connecté",
        "Editar": "Modifier",
        "Editar cuenta": "Modifier le compte",
        "Editar la pantalla": "Modifier cet écran",
        "Editar mi perfil": "Modifier mon profil",
        "Editar movimiento": "Modifier l’opération",
        "Editar préstamo": "Modifier le prêt",
        "Editar tarjeta": "Modifier la carte",
        "Educación": "Éducation",
        "Efectivo": "Espèces",
        "el de fábrica": "celle par défaut",
        "El de la app": "Celle de l’app",
        "El dictado no está disponible ahora mismo.": "La dictée n’est pas disponible pour le moment.",
        "El icono de la app": "L’icône de l’app",
        "el mes pasado no hubo gastos": "aucune dépense le mois dernier",
        "El micrófono lo está usando otra app. Ciérrala y vuelve a intentarlo.": "Une autre app utilise le micro. Ferme-la et réessaie.",
        "El presupuesto": "Le budget",
        "El rótulo debajo de cada icono": "Le libellé sous chaque icône",
        "El tuyo ahora": "Le tien en ce moment",
        "Eliminar": "Supprimer",
        "Eliminar mi cuenta": "Supprimer mon compte",
        "Empezar": "Commencer",
        "Empezar de nuevo": "Recommencer",
        "en": "en",
        "en {n} d": "dans {n} j",
        "En aro": "En anneau",
        "En barra": "En barre",
        "En bloques": "En blocs",
        "En esa cuenta hay {h}. No alcanza para apartar {c}.": "Ce compte a {h}. Pas assez pour mettre {c} de côté.",
        "En esa cuenta hay {h}. No alcanza para pagar {c}.": "Ce compte a {h}. Pas assez pour payer {c}.",
        "En qué fue": "C’était pour quoi",
        "En una casa de bolsa o app": "Chez un courtier ou dans une app",
        "En uso": "Utilisé",
        "Enseñar": "Afficher",
        "Enseñar el dinero": "Afficher l’argent",
        "Enseñar la tendencia": "Afficher la tendance",
        "Entendido": "Compris",
        "Entidad o persona (opcional)": "Organisme ou personne (facultatif)",
        "Entretenimiento": "Loisirs",
        "Entró": "Entrée",
        "Entró este mes": "Entré ce mois-ci",
        "Enviar": "Envoyer",
        "Es lo que tendrías si hoy pagaras todas tus deudas.": "C’est ce que tu aurais si tu payais tout aujourd’hui.",
        "Esconder las cifras": "Masquer les chiffres",
        "Ese préstamo ya está pagado.": "Ce prêt est déjà remboursé.",
        "Esquinas redondeadas": "Coins arrondis",
        "este equipo": "cet appareil",
        "este mes": "ce mois-ci",
        "Este mes": "Ce mois-ci",
        "Este mes va corto: empieza por los gastos variables.": "Ce mois est serré : commence par les dépenses variables.",
        "Este teléfono no la trae. Chino sigue funcionando con la IA de Chinola.": "Ce téléphone ne l’a pas. Chino continue avec l’IA de Chinola.",
        "Esto no se puede deshacer.": "C’est définitif.",
        "Esto revierte su efecto en los saldos. No se puede deshacer.": "Cela annule son effet sur les soldes. C’est irréversible.",
        "explica el": "représente",
        "explican el": "représentent",
        "Fecha": "Date",
        "Fijo": "Fixe",
        "Fijos": "Fixes",
        "Fondo de inversión": "Fonds d’investissement",
        "Fondos mutuos o de pensión voluntaria": "Fonds communs ou de retraite volontaire",
        "Gastado": "Dépensé",
        "Gastado en": "Dépensé en",
        "Gastado en el período": "Dépensé sur la période",
        "gastas {n}% más que el mes pasado": "tu dépenses {n} % de plus que le mois dernier",
        "gastas {n}% menos que el mes pasado": "tu dépenses {n} % de moins que le mois dernier",
        "Gastaste": "Tu as dépensé",
        "Gasto": "Dépense",
        "Gasto con ella": "Dépenser avec",
        "Gastos": "Dépenses",
        "Gimnasio, club, supermercado": "Salle de sport, club, supermarché",
        "Gráfica": "Graphique",
        "Guardado, no para gastar mañana": "Mis de côté, pas pour demain",
        "Guardar": "Enregistrer",
        "Guardar archivo": "Enregistrer le fichier",
        "Hablar con Chino": "Parler à Chino",
        "hace {n} días": "il y a {n} jours",
        "hace {n} h": "il y a {n} h",
        "hace {n} min": "il y a {n} min",
        "Hace falta tu permiso para dictar.": "La dictée a besoin de ton autorisation.",
        "Hace falta tu permiso para usar el micrófono.": "Le micro a besoin de ton autorisation.",
        "hace más de un mes": "il y a plus d’un mois",
        "hace un momento": "à l’instant",
        "Hacer {r}": "Passer en {r}",
        "hoy": "aujourd’hui",
        "Hoy": "Aujourd’hui",
        "Ibas a": "Tu étais à",
        "Icono": "Icône",
        "Ingreso": "Revenu",
        "Ingresos": "Revenus",
        "Integrada": "Intégré",
        "Inversión": "Investissement",
        "invierte": "investir",
        "Invitar": "Inviter",
        "Ir a organizar el panel": "Organiser le tableau de bord",
        "La forma de la tarjeta y lo apretada que va la lista. Son de este teléfono, no de la libreta.": "La forme de la carte et la densité de la liste. Elles sont de ce téléphone, pas du carnet.",
        "La suma": "La somme",
        "La tarjeta de arriba": "La carte du haut",
        "Las cifras del mes en tarjetas de su color, con más vida": "Les chiffres du mois dans des cartes de leur couleur, plus vivantes",
        "Las pestañas": "Les onglets",
        "Letra": "Police",
        "Letra de los títulos": "Police des titres",
        "Letra del texto": "Police du texte",
        "Libretas y permisos": "Carnets et permissions",
        "Límite": "Plafond",
        "Línea de crédito": "Ligne de crédit",
        "Lisa": "Unie",
        "Lista. Lo que le preguntes no sale de este teléfono.": "Prête. Ce que tu lui demandes ne quitte pas ce téléphone.",
        "Listo": "Terminé",
        "Lo que cargas en la cartera": "Ce que tu as dans le portefeuille",
        "Lo que debes": "Ce que tu dois",
        "Lo que entra, lo que sale y lo que apartas. Hay una que se distingue con daltonismo.": "Ce qui entre, ce qui sort et ce que tu mets de côté. L’une d’elles convient au daltonisme.",
        "Lo que entró, lo que salió y lo que te queda, de un vistazo.": "Ce qui est entré, ce qui est sorti et ce qui reste, d’un coup d’œil.",
        "Lo que le prestaste a un amigo o familiar": "Ce que tu as prêté à un ami ou à la famille",
        "Lo que tienes": "Ce que tu as",
        "Lo último que pasó": "Ce qui s’est passé",
        "Los centavos": "Les centimes",
        "Mantén pulsada para mover · pellizca para el tamaño": "Maintiens pour déplacer · pince pour la taille",
        "Mantén pulsada una tarjeta para moverla, pellizca para cambiar su tamaño, y en su menú la ocultas o la quitas.": "Maintiens une carte pour la déplacer, pince pour changer sa taille, et depuis son menu masque-la ou retire-la.",
        "Mantén pulsada una tarjeta para su menú. Se mueve con las flechas y se estira con el ancho.": "Appuie longuement sur une carte pour son menu. Déplace-la avec les flèches et étire-la avec la largeur.",
        "Mantén pulsado para hablar": "Maintiens appuyé pour parler",
        "Marca un movimiento como «se repite cada mes»": "Marque une opération comme « se répète chaque mois »",
        "Me deben": "On me doit",
        "Media": "Moyenne",
        "Membresía": "Adhésion",
        "Menú de abajo": "Menu du bas",
        "Mes pasado": "Le mois dernier",
        "meses": "mois",
        "Meta": "Objectif",
        "Metales": "Métaux",
        "Metro, OMSA, peaje": "Métro, bus, péages",
        "Mi cuenta": "Mon compte",
        "Mi plan": "Mon offre",
        "Miembros": "Membres",
        "Modo": "Mode",
        "Moneda": "Devise",
        "Monto total": "Montant total",
        "Movimientos": "Opérations",
        "Movimientos de esta cuenta": "Opérations de ce compte",
        "Movs.": "Opér.",
        "Nada con ese nombre": "Rien à ce nom",
        "Nada por pagar": "Rien à payer",
        "Nada que se repita": "Rien qui se répète",
        "Ninguna": "Aucune",
        "No": "Non",
        "No disponible": "Indisponible",
        "No encuentro esa meta.": "Je ne trouve pas cet objectif.",
        "No encuentro esa tarjeta.": "Je ne trouve pas cette carte.",
        "No encuentro ese préstamo.": "Je ne trouve pas ce prêt.",
        "No hay movimientos": "Aucune opération",
        "No hay nada del año pasado": "Rien de l’an dernier",
        "No se pudo abrir el selector": "Impossible d’ouvrir le sélecteur",
        "No se pudo encender el micrófono.": "Le micro n’a pas pu être activé.",
        "No se pudo leer ese archivo": "Impossible de lire ce fichier",
        "Nombre": "Nom",
        "Nombre (ej. Cuenta principal)": "Nom (ex. Compte principal)",
        "Nombre (ej. Préstamo del carro)": "Nom (ex. Prêt auto)",
        "Nombre (ej. Visa Popular)": "Nom (ex. Visa Popular)",
        "Nombres en el menú": "Noms dans le menu",
        "Nueva cuenta": "Nouveau compte",
        "Nueva libreta": "Nouveau carnet",
        "Nueva meta": "Nouvel objectif",
        "Nueva tarjeta": "Nouvelle carte",
        "Nuevo movimiento": "Nouvelle opération",
        "Nuevo préstamo": "Nouveau prêt",
        "Objetivo": "Objectif",
        "Oculta": "Masquée",
        "Ocultar": "Masquer",
        "Ocultar el dinero": "Masquer l’argent",
        "Operador (ej. Metro)": "Opérateur (ex. Métro)",
        "Organiza tu panel": "Organise ton tableau",
        "Organizar el panel": "Organiser le tableau",
        "Oro o plata": "Or ou argent",
        "Oscuro": "Sombre",
        "Otra con saldo": "Une autre avec un solde",
        "Otros": "Autres",
        "Pagado": "Payé",
        "Pagado con": "Payé avec",
        "Pagar la tarjeta": "Payer la carte",
        "Pago": "Paiement",
        "Pago de {p}": "Paiement de {p}",
        "pago en {n} d": "paiement dans {n} j",
        "Pagos registrados": "Paiements enregistrés",
        "Panel del resumen": "Tableau de bord",
        "Para gastar": "À dépenser",
        "Para lo que pagas siempre: renta, luz, colegio": "Pour ce que tu paies toujours : loyer, électricité, école",
        "Para mirar el teléfono en la calle": "Pour regarder ton téléphone dans la rue",
        "Parar": "Arrêter",
        "Pasivos": "Passifs",
        "Pastillas": "Pastilles",
        "Patrimonio": "Patrimoine",
        "PayPal, tPago, Qik…": "PayPal, tPago, Qik…",
        "pedir prestado / prestar": "emprunter / prêter",
        "Perfil": "Profil",
        "Periodo": "Période",
        "Personal": "Personnel",
        "Plan": "Plan",
        "Pon cuánto vas a aportar.": "Indique combien tu verses.",
        "Pon cuánto vas a pagar.": "Indique combien tu paies.",
        "Pon un presupuesto y te lo reparto": "Fixe un budget et je le répartis",
        "Ponle presupuesto a tus categorías": "Mets un budget sur tes catégories",
        "por día": "par jour",
        "Preguntarle a Chino": "Demander à Chino",
        "Prepago y membresías": "Prépayé et adhésions",
        "Préstamo del banco, del carro o de alguien": "Un prêt de la banque, pour la voiture, ou de quelqu’un",
        "Préstamos": "Prêts",
        "Préstamos y fiados": "Prêts et ardoises",
        "préstamos y tarjetas": "prêts et cartes",
        "Presupuesto de {n}": "Budget de {n}",
        "Probar otro método": "Essayer autrement",
        "promedio del mes": "moyenne du mois",
        "Prueba con un archivo de Chinola (.json) o un CSV del banco.": "Essaie un fichier Chinola (.json) ou un CSV de la banque.",
        "Puedes tener varios a la vez y elegir con cuál entrar. Todos son gratis.": "Tu peux en avoir plusieurs et choisir avec laquelle entrer. Toutes sont gratuites.",
        "que en el mismo mes de {a}": "que le même mois de {a}",
        "Qué grupos se ven": "Quels groupes s’affichent",
        "Qué periodo miras": "Quelle période tu regardes",
        "Qué sabe hacer Chino": "Ce que Chino sait faire",
        "Qué se ve arriba": "Ce qui s’affiche en haut",
        "Quedan": "Il reste",
        "Quitar": "Retirer",
        "Quitar de la libreta": "Retirer du carnet",
        "Quitar del panel": "Retirer du tableau",
        "Rango": "Plage",
        "Registrar abono": "Enregistrer un versement",
        "Registrar cuota": "Noter une échéance",
        "Registrar pago": "Enregistrer un paiement",
        "Repetir cada mes": "Répéter chaque mois",
        "Reportar un problema": "Signaler un problème",
        "Resumen": "Résumé",
        "Resumen del mes": "Résumé du mois",
        "Saldo actual": "Solde actuel",
        "Saldo de la tarjeta": "Solde de la carte",
        "Saldo disponible": "Solde disponible",
        "Saldo o puntos": "Solde ou points",
        "Salió este mes": "Sorti ce mois-ci",
        "Salud": "Santé",
        "seguidos sin gastar": "d’affilée sans dépenser",
        "Seguridad": "Sécurité",
        "Servicio (ej. PayPal)": "Service (ex. PayPal)",
        "Servicios": "Services",
        "Si hoy pagas todo, te quedan": "Si tu paies tout aujourd’hui, il te reste",
        "si sigues gastando igual": "si tu continues à dépenser pareil",
        "Sin banco": "Sans banque",
        "Sin centavos": "Sans centimes",
        "Sin color propio: la cabecera toma el fondo de la pantalla.": "Sans couleur propre : l’en-tête prend le fond de l’écran.",
        "Sin cuotas este mes: buen momento para aportar a tus metas.": "Pas de mensualités ce mois-ci : bon moment pour alimenter tes objectifs.",
        "Sin gastos este mes": "Aucune dépense ce mois",
        "Sin nada con qué bloquear": "Rien pour verrouiller",
        "Solo en Android": "Android seulement",
        "Subir": "Monter",
        "Subrayadas": "Soulignés",
        "Suelta para cancelar": "Relâche pour annuler",
        "Tamaño de la letra": "Taille du texte",
        "Tarjeta de crédito": "Carte de crédit",
        "Tarjeta de transporte": "Carte de transport",
        "Tarjeta escolar": "Carte scolaire",
        "Tarjetas": "Cartes",
        "tarjetas + préstamos": "cartes + prêts",
        "Tarjetas con color": "Cartes en couleur",
        "Tarjetas de crédito": "Cartes de crédit",
        "Tarjetas y crédito": "Cartes et crédit",
        "Te deben": "On te doit",
        "Te escucho…": "Je t’écoute…",
        "Te falta cobrar": "Reste à encaisser",
        "Te falta pagar": "Reste à payer",
        "Te pasaste": "Dépassé de",
        "Te pasaste por": "Dépassé de",
        "Te queda": "Il te reste",
        "te queda este mes": "il te reste ce mois-ci",
        "Te queda si pagas todo": "Il te reste si tu paies tout",
        "Tema de día": "Thème de jour",
        "Tema de noche": "Thème de nuit",
        "Tendencia": "Tendance",
        "Tienes": "Tu as",
        "Tipo": "Type",
        "Toca el botón para terminar": "Touche le bouton pour terminer",
        "todo": "tout",
        "Todo": "Tout",
        "Todo el saldo": "Tout le solde",
        "Todos": "Tous",
        "Total": "Total",
        "Transferencia": "Virement",
        "Transferir": "Transférer",
        "Transporte": "Transport",
        "tú": "toi",
        "Tu límite": "Ta limite",
        "Tu patrimonio este mes": "Ton patrimoine ce mois-ci",
        "Tu teléfono no tiene Face ID, huella ni código. Ponle uno en Ajustes y vuelve a encenderlo.": "Ton téléphone n’a ni Face ID, ni empreinte, ni code. Ajoute-en un dans Réglages et réactive ceci.",
        "Tu teléfono puede, pero hay que bajarla primero.": "Ton téléphone peut, mais il faut d’abord la télécharger.",
        "Tus cuotas fijas son {monto}, un {pct}% de tus ingresos.": "Tes mensualités fixes sont de {monto}, soit {pct}% de tes revenus.",
        "Últimos 12 meses": "12 derniers mois",
        "Últimos 3 meses": "3 derniers mois",
        "Un momento…": "Un instant…",
        "Variable": "Variable",
        "Variables": "Variables",
        "Vas a": "Tu es à",
        "Ver detalle": "Voir le détail",
        "Ver el presupuesto": "Voir le budget",
        "Ver la tendencia": "Voir la tendance",
        "Ver más": "Voir plus",
        "Verificación en dos pasos": "Vérification en deux étapes",
        "Vidrio": "Verre",
        "visto": "vu",
        "Vivienda": "Logement",
        "Volver": "Retour",
        "Volver a intentarlo": "Réessayer",
        "y": "et",
        "Ya lo pagué": "Déjà payé",
        "Ya pagado": "Déjà payé",
        "Ya pasaste el presupuesto del mes": "Tu as dépassé le budget du mois",
        "Yo debo": "Je dois"
    ]

    /// La tabla de un idioma, o ninguna si es español —que es como están
    /// escritos los textos en el propio Swift—.
    static func de(_ idioma: String) -> [String: String] {
        switch idioma {
        case "en": return en
        case "fr": return fr
        default: return [:]
        }
    }
}
